### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by amree** [amree/thebayaran#1]
- [x] Update page after shop has been created [Enhancement] 
- [x] Visitor shouldn't have to login when visiting order's form [Bug]
- [x] Redirection after customer submit the order [Bug]
- [x] Add Tracking Number and Post's vendor field [Feature]
- [x] Use shop's name as the referral key [Feature]
- [x] Email notifications every time the form changed [Feature]
- [x] User shouldn't be able to access `Shop#new` when he/she has created the shop [Bug]
- [x] Shop name cannot be changed [Feature]
- [x] Save user agent string for every customer [Feature]
- [x] Save customer's original link [Feature]
- [ ] Add pagination
- [x] 'Menunggu Pengesahan' should be the default value for the status [Enhancement]

**Comment by amree** [comment]
Closes since all the to do items are transformed to issues
